### ISSUE TITLE
sqlite trigram tokenizer word_similarity()

### ISSUE THREAD

**Issue by chapmanjacobd** [simonw/sqlite-fts5-trigram#2]
I would like to find near-duplicates using the `trigram` index in SQLITE. postgres has a word_similarity function (and the `<<->` operator). I'm assuming there is no SQLITE equivalent.

Have you done something similar before or have any ideas for querying directly from fts tables to do this via SQL?

edit: 

I was able to get the results that I wanted by following your blog post here: https://til.simonwillison.net/sqlite/related-content

https://github.com/chapmanjacobd/library/compare/v1.27.006...v1.28.001

**Comment by simonw** [comment]
I've tried using the Python Jellyfish library for this, exposed to SQLite via registering those Python functions as SQL functions. I have a plugin for that here: https://datasette.io/plugins/datasette-jellyfish

I've not thought to try using trigram for this - it certainly sounds like it might work. The SQLite forum might be a good place to ask about that: https://sqlite.org/forum/forummain
